id: A4A0A838A
title: Rule against ordination of Tīrthkas
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.891658
  last_modified_at: 2022-03-01 22:10:19.891661
