id: A4A0A838A
title: CII_Teacher II, Maskarin Gośālīputra
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.762033
  last_modified_at: 2022-03-01 22:10:19.762052
