id: A4A0A838A
title: Buddha’s smile
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.735694
  last_modified_at: 2022-03-01 22:10:19.735700
