id: A4A0A838A
title: Maudgalyāyana’s journey to Hell and Heaven
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.882937
  last_modified_at: 2022-03-01 22:10:19.882940
