id: A4A0A838A
title: Why Śāriputra was wise 1
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.912904
  last_modified_at: 2022-03-01 22:10:19.912907
