id: A4A0A838A
title: Why Śāriputra was wise 2
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.914002
  last_modified_at: 2022-03-01 22:10:19.914005
