id: A4A0A838A
title: Why Saṃgharakṣita was born in a rich family
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.910905
  last_modified_at: 2022-03-01 22:10:19.910908
