id: A4A0A838A
title: Why Koṣṭhila is pratisaṃvedin
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.907665
  last_modified_at: 2022-03-01 22:10:19.907668
