id: A4A0A838A
title: Mātṛghātaka
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.885577
  last_modified_at: 2022-03-01 22:10:19.885580
