id: A4A0A838A
title: CII_Teacher I, Pūraṇa Kāśyapa
type: translation
source_metadata:
  languages:
  - bo
  - sa
  datatype: PlainText
  created_at: 2022-03-01 22:10:19.760216
  last_modified_at: 2022-03-01 22:10:19.760224
